spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.55.243:3306/kosmos?serverTimezone=GMT%2B8
    username: root
    password: QMy910328
    tomcat:
      max-wait: 30000  # tomcat pool , Number of ms to wait before throwing an exception if no connection is available. 112.80.52.178 192.168.0.31: 1522/citgctest
      max-idle: 5
      max-active: 5 # Maximum number of active connections that can be allocated from this pool at the same time.
      test-on-borrow: true # Validate the connection before borrowing it from the pool.
      validation-query: select 1 from dual
